name: Build & Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run eisstadion
        run: python eisstadion_kempten.py

      - name: run esc team
        run: python esc_kempten_team.py

      - name: run esc
        run: python esc_kempten.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
